# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - aimeos

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_41ec0909ee48437faa08ef66a1f36da8 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e98304797a5e45d390fd2caa2985b3dc }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_41ec0909ee48437faa08ef66a1f36da8 }}/mcr.microsoft.com/appsvc/ubuntu:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'aimeos'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f5ba417f6c59429099c2b039accb1209 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_41ec0909ee48437faa08ef66a1f36da8 }}/mcr.microsoft.com/appsvc/ubuntu:${{ github.sha }}'